### ISSUE TITLE
Add a !ready command when a pug starts with a 2 min timer, kicks anyone who didn't ready up on time

### ISSUE THREAD

**Issue by HammerKick** [Doezer/discord-gather#24]

**Comment by Doezer** [comment]
- when in state "teams created"
- start x min timer
- tell registered players to type !ready
- if not ready after timer > go back to creation state

**Comment by Doezer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [commande !ready](https://trello.com/c/FcKKQdLH/7-commande-ready)

**Comment by Doezer** [comment]
Added in https://github.com/Doezer/discord-gather/commit/5ea20253ec26264ef78d7bbc7c0529ede839318a
